### ISSUE TITLE
Why are concourse and CF tied to BOSH on the scripts?

### ISSUE THREAD

**Issue by luan** [cloudfoundry/mega-ci#9]
It seems to me that I should be able to setup a BOSH environment and they build on it by adding concourse or CF or whatever later. There's also quite a bit of duplication in the README about setting up some of the bosh properties for the script on both concourse and CF scenarios. It is also not clear whether I can have both CF and concourse on that same environment.

**Comment by Amit-PivotalLabs** [comment]
The reason it's like this is so that everything is captured in one cloudformation template.  Rather than creating AWS resources just for BOSH, and then separately creating a new cloudformation template, with, for example, new Concourse subnets that reference the VPC from the previous template used to set up BOSH, all the cloud-formating is done in one place.

We're currently not trying to solve the arbitrary use case, just Concourse and CF, with the minimal flexibility needed to support things like diego (e.g. define an extra ELB for SSH, some extra subnets for Diego, etc.) but not arbitrary AWS provisioning.

----

The script for setting up CF doesn't also prepare the environment for Concourse.  On the other hand, the script for prepare Concourse *does* let you also prepare the same environment for CF:

> If you want to deploy full Cloud Foundry into the same AWS stack where you will deploy Concourse, you shold provide an SSL certificate for the domain where Cloud Foundry will be accessible. If you provide these, the cert and pem will be uploaded to your AWS account. The script will look for the files at certs/cf.key and certs/cf.pem.

This behaviour will actually go away, it will be simplified so that the Concourse tool is just for preparing Concourse, and the other one is just for CF, and we won't have one tool that tries to support too many variations.

**Comment by Amit-PivotalLabs** [comment]
Thanks very much for this feedback @luan, we're marking this repo as being under heavy re-construction, and we'll incorporate this information in the new incarnation. (I'll copy-paste this message to the other issues you opened, for anyone in the future coming across any of them).
